### ISSUE TITLE
Not working inside scroll view

### ISSUE THREAD

**Issue by achinverma** [ATHBK/AvatarTinderView#3]
Hi , your library is crashing inside scroll view. @ATHBK  please can you look at this crash .

 ```
<ScrollView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:fillViewport="true">

        <com.athbk.avatarview.TinderRecyclerView
            android:id="@+id/profile_pics_recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:visibility="visible"
            app:numberColoum="4"
            app:spanCount="4">

        </com.athbk.avatarview.TinderRecyclerView>

    </ScrollView>
```

```
E/InputEventReceiver: Exception dispatching input event.
11-28 11:10:36.236 16613-16613/com.get.spota E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-28 11:10:36.238 16613-16613/com.get.spota E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to read from field 'int com.athbk.avatarview.utils.SpannedGridLayoutManager$GridCell.row' on a null object reference
                                                                     at com.athbk.avatarview.utils.SpannedGridLayoutManager.getRowIndex(SpannedGridLayoutManager.java:416)
                                                                     at com.athbk.avatarview.utils.SpannedGridLayoutManager.recycleRow(SpannedGridLayoutManager.java:520)
                                                                     at com.athbk.avatarview.utils.SpannedGridLayoutManager.scrollVerticallyBy(SpannedGridLayoutManager.java:237)
                                                                     at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1695)
                                                                     at android.support.v7.widget.RecyclerView.onGenericMotionEvent(RecyclerView.java:2978)
                                                                     at android.view.View.dispatchGenericMotionEventInternal(View.java:8581)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8562)
                                                                     at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                     at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1870)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8555)
                                                                     at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                     at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1870)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8555)
                                                                     at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                     at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1870)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8555)
                                                                     at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                     at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1870)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8555)
                                                                     at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                     at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1870)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8555)
                                                                     at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                     at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1870)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8555)
                                                                     at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1919)
                                                                     at android.view.ViewGroup.dispatchGenericPointerEvent(ViewGroup.java:1870)
                                                                     at android.view.View.dispatchGenericMotionEvent(View.java:8555)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2377)
                                                                     at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1729)
                                                                     at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2778)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:83)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:83)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2344)
                                                                     at android.view.View.dispatchPointerEvent(View.java:8668)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
```

**Comment by achinverma** [comment]
@ATHBK , please can you help me in the above issue.

**Comment by ATHBK** [comment]
Hi. I try change code like you and run, but It is still working. 
Please add more info or source code and I will check it.
In addition, I encourage you not to use TinderRecyclerView inside ScrollView because both of them is scroll. Scroll should not be in scroll.

Best regards !

**Comment by achinverma** [comment]
@ATHBK , i have resolved this crash issue inside scrollveiw

**Comment by achinverma** [comment]
@ATHBK , i have one more question, please can you tell me how can i disable this drag for particular item, i mean to say - in the 2nd row i have 4 items horizontal and i want to disable the drag & drop for the last item , mean, on Longclick , i don't want to allow drag .  just i want to disable drag drop for particular item.
when we select an item  onItemSelected() method will be called.
```
 @Override
        public void onItemSelected() {
            super.onItemSelected();
            layout.setAlpha(0.5f);
            Log.e("onItemSelected", "onItemSelected");
        }
```

Hey, @ATHBK are you there?
